name: vyrax_rules
description: Rule package placeholders for future Flutter-specific diagnostics.
version: 0.1.8
repository: https://github.com/vyraxsoft/vyrax

environment:
  sdk: ^3.9.0

dependencies:
  vyrax_core: ^0.1.8

dev_dependencies:
  test: ^1.26.3
